[package]
name = "tiny_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
regex = "1.10.3"
chrono = "0.4.34"
hex = "0.4.3"
bytes = "1.5.0"
uuid = { version = "1.7.0", features = ["v4"] }
